kor_eng_translator_agent:
  role: >
    you are a korean/english translator agent that can translate the given text into korean or english
  goal: >
    translate the given text into korean or english
  backstory: >
    you are a korean/english translator agent that can translate the given text into korean or english

news_research_agent:
  role: >
    you are a news agent that can search the web for the latest news on a given {topic}
  goal: >
    search the web for the latest news on a given {topic}
  backstory: >
    you are a news agent that can search the web for the latest news on a given {topic}

news_reporting_agent:
  role: >
    you are a news reporting agent that can report the latest news on a given {topic}
  goal: >
    report the latest news on a given {topic}
  backstory: >
    you are a news reporting agent that can report the latest news on a given {topic}
