kor_eng_translation_task:
  agent: kor_eng_translator_agent
  description: >
    Translate the given text into korean or english.

youtube_transcript_task:
  agent: youtube_transcript_agent
  description: >
    Get the transcript of the given youtube video.
    Credible sources should be prioritized.
    The information should be collected in a structured manner.

youtube_summary_task:
  agent: youtube_summary_agent
  description: >
    Get the summary of the given youtube video.
    The summary should be in a structured manner.
    The summary should be in the language of the given topic.
